// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CocheraTp.Models;

public partial class CLIENTE
{
    public int id_cliente { get; set; }

    public string nombre { get; set; }

    public string apellido { get; set; }

    public int? id_tipo_doc { get; set; }

    public string nro_documento { get; set; }

    public string direccion { get; set; }

    public string telefono { get; set; }

    public string email { get; set; }

    public int? id_iva_condicion { get; set; }

    public virtual ICollection<FACTURA> FACTURAs { get; set; } = new List<FACTURA>();

    public virtual IVA_CONDICIONE id_iva_condicionNavigation { get; set; }

    public virtual TIPOS_DOC id_tipo_docNavigation { get; set; }
}