// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CocheraTp.Models;

public partial class IVA_CONDICIONE
{
    public int id_iva_condicion { get; set; }

    public string descripcion { get; set; }

    public virtual ICollection<CLIENTE> CLIENTEs { get; set; } = new List<CLIENTE>();
}