// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CocheraTp.Models;

public partial class MARCA
{
    public int id_marca { get; set; }

    public string nombre_marca { get; set; }

    public virtual ICollection<MODELO> MODELOs { get; set; } = new List<MODELO>();
}