// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CocheraTp.Models;

public partial class USUARIO
{
    public int id_usuario { get; set; }

    public string usuario1 { get; set; }

    public string contrasenia { get; set; }

    public int? id_rol { get; set; }

    public virtual ICollection<FACTURA> FACTURAs { get; set; } = new List<FACTURA>();

    public virtual ROLE id_rolNavigation { get; set; }
}