// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CocheraTp.Models;

public partial class VEHICULO
{
    public int id_vehiculo { get; set; }

    public string patente { get; set; }

    public string color { get; set; }

    public int? id_tipo_vehiculo { get; set; }

    public int? id_modelo { get; set; }

    public virtual ICollection<DETALLE_FACTURA> DETALLE_FACTURAs { get; set; } = new List<DETALLE_FACTURA>();

    public virtual ICollection<REMITO> REMITOs { get; set; } = new List<REMITO>();

    public virtual MODELO id_modeloNavigation { get; set; }

    public virtual TIPOS_VEHICULO id_tipo_vehiculoNavigation { get; set; }
}